### ISSUE TITLE
Possibility to edit/ delete collections

### ISSUE THREAD

**Issue by DylanGomez** [outl1ne/nova-media-hub#32]
When making collections, once the collection is made it can not be edited or deleted by the user.

**Comment by robindrost** [comment]
Images and video are default. Custom collections are not visible anymore when there are no items left in that collection.

**Comment by richard-raadi** [comment]
Editing a collection name is not something we'll focus on, currently. 

Feel free to create a pull request if it's a strict requirement for your project.

Otherwise like Robin said, the collection will be removed from Nova if there's no media left in the collection.

For now I will be closing this issue as there is no issue.
